### ISSUE TITLE
Use font_style:glow for selected error location once on ST4?

### ISSUE THREAD

**Issue by 0pdd** [frou/Humid#2]
The puzzle `0-fd4ad053` from #0 has to be resolved: 

https://github.com/frou/Humid/blob/7c474754e4a74c3a8c71ad9383859caa7e1fac45/Humid.sublime-color-scheme#L146-L146

The puzzle was created by Duncan Holm on 02-Mar-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by frou** [comment]
Nah
